CREATE USER ${DB_REPL_USER} REPLICATION LOGIN PASSWORD '{DB_REPL_PASSWORD}';
ALTER USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
CREATE DATABASE ${DB_DATABASE};
GRANT ALL PRIVILEGES ON DATABASE ${DB_DATABASE} TO ${DB_USER};

\c ${DB_DATABASE};

CREATE TABLE IF NOT EXISTS phones (
    id SERIAL PRIMARY KEY,
    phone VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS emails (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL
);

INSERT INTO emails (email) VALUES ('test@w.ru');
INSERT INTO phones (phone) VALUES ('80000000000');
